spring:
  application:
    name: n-user-service
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: true
  mail:
    host: smtp.gmail.com
    username: hsciapan@gmail.com
    password: "crzhhhizdfvljrld"
    admin-mail: hirrafes@gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            trust: smtp.gmail.com
  datasource:
    url: jdbc:postgresql://n-user-db:5432/n-user-db
    username: postgres
    password: mitrandir
    driver-class-name: org.postgresql.Driver

jwt:
  key: Nikon1234
  expiration: 3600000
  bearer: 'Bearer '
  begin-index: 7

server:
  port: 8080
  domain: http://n-user-service:8080/

security:
  encoder:
    strength: 12